# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18779fead276090ffb34f2061590acc1eb5a376cb67b8753b30bbd63d2b261cee0b95cb781ebaebaf06b302fab25284be12a1c00528dbcebf75c551f2568975

test:
  secret_key_base: 45f0c2dc883d5e52a893a00873454d0640a28d9f2c06da8ba7f8560def02a5faf64b52710ccfc377e9c14e6062a0c20f1bbe0d0e230b7ceb163ae25ff63ef48f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
